module.exports = [{
	"text": "浅蓝",
	"color": "#85B8CF",
	"text_color": "#ffffff"
}, {
	"text": "深蓝",
	"color": "#0072ff",
	"text_color": "#ffffff"
}, {
	"text": "亮蓝",
	"color": "#12FFF7",
	"text_color": "#ffffff"
}, {
	"text": "桃红",
	"color": "#FF6B6B",
	"text_color": "#ffffff"
}, {
	"text": "粉色",
	"color": "#FC9F9D",
	"text_color": "#ffffff"
}, {
	"text": "深绿",
	"color": "#52c234",
	"text_color": "#ffffff"
}, {
	"text": "浅绿",
	"color": "#90C652",
	"text_color": "#ffffff"
}, {
	"text": "深紫",
	"color": "#6E48AA",
	"text_color": "#ffffff"
}, {
	"text": "浅紫",
	"color": "#9D50BB",
	"text_color": "#ffffff"
}, {
	"text": "黑紫",
	"color": "#4B1248",
	"text_color": "#ffffff"
}, {
	"text": "黄绿",
	"color": "#90C652",
	"text_color": "#ffffff"
}, {
	"text": "棕色",
	"color": "#D8AA5A",
	"text_color": "#ffffff"
}, {
	"text": "棕色",
	"color": "#D8AA5A",
	"text_color": "#ffffff"
}, {
	"text": "粉色",
	"color": "#FC9F9D",
	"text_color": "#ffffff"
}, {
	"text": "浅蓝",
	"color": "#85B8CF",
	"text_color": "#ffffff"
}, {
	"text": "黄绿",
	"color": "#90C652",
	"text_color": "#ffffff"
}, {
	"text": "樱色",
	"color": "#D8AA5A",
	"text_color": "#FBD3E9"
}, {
	"text": "粉色",
	"color": "#FC9F9D",
	"text_color": "#FC9F9D"
}, {
	"text": "白色字",
	"color": "#ffffff",
	"text_color": "#ffffff"
}, {
	"text": "黑色字",
	"color": "#85B8CF",
	"text_color": "#000000"
}, {
	"text": "灰色字",
	"color": "#90C652",
	"text_color": "#343434"
}, ]
